<div class="basGrid" style="width:600px;">
<form method="post" action="<?php echo $this->baseUrl();?>/user/index/save">
    <table>
        <thead>
            <th colspan="2">Add user information</th>
        </thead>
        <tr>
            <td style="width: 150px;"><?php echo $this->userForm->first_name->getLabel();?></td>
            <td><?php echo $this->userForm->first_name;?></td>
        </tr>
         <tr>
            <td><?php echo $this->userForm->last_name->getLabel();?></td>
            <td><?php echo $this->userForm->last_name;?></td>
        </tr>
         <tr>
            <td><?php echo $this->userForm->email_address->getLabel();?></td>
            <td><?php echo $this->userForm->email_address;?></td>
        </tr>
        <tr>
            <td><?php echo $this->userForm->type->getLabel();?></td>
            <td><?php echo $this->userForm->type;?></td>
        </tr>
		 <tr class="salesAgentField">
            <td><?php echo $this->userForm->entity->getLabel();?></td>
            <td><?php echo $this->userForm->entity;?></td>
        </tr>
       
        <tr class="salesAgentField">
            <td><?php echo $this->userForm->address->getLabel();?></td>
            <td><?php echo $this->userForm->address;?></td>
        </tr>
        <tr class="salesAgentField">
            <td><?php echo $this->userForm->agent_name->getLabel();?></td>
            <td><?php echo $this->userForm->agent_name;?></td>
        </tr>
        <tr class="salesAgentField">
            <td><?php echo $this->userForm->position->getLabel();?></td>
            <td><?php echo $this->userForm->position;?></td>
        </tr>
		<tr>
			<td>&nbsp;</td>
		    <td><?php echo $this->userForm->rights;?></td>
		</tr>
         <tr>
            <td></td>
            <td><?php echo $this->userForm->submit;?></td>
        </tr>
    </table>
</form>
</div>    

<script>

$("#type").change(function(){
   toggleSalesAgentFields(); 
});

function toggleSalesAgentFields()
{
    if($("#type").val() == 'salesagent')
        $(".salesAgentField").show();
    else
        $(".salesAgentField").hide();
}

toggleSalesAgentFields();

</script>
