<form method="post" action="<?php echo $this->baseUrl();?>/user/index/update-password">
<input type="hidden" name="user_id" value="<?php echo $this->userId;?>"/>    
<div class="basGrid" style="width:500px;">
    <table>
        <thead>
            <th colspan="2">Change password</th>
        </thead>
        <tr>
            <td>Old password</td>
            <td><?php echo $this->changePassword->oldPassword;?></td>
        </tr>
        <tr>
            <td>New password</td>
            <td><?php echo $this->changePassword->newPassword;?></td>
        </tr>
        <tr>
            <td>Re-type password</td>
            <td><?php echo $this->changePassword->verifyPassword;?></td>
        </tr>
         <tr>
            <td>Old password</td>
            <td><input type="submit"  value="Submit" /></td>
        </tr>
    </table>
</div>
</form> 

