<form method="post" action="<?php echo $this->baseUrl();?>/user/index/assign-project">
<input type="hidden" name="user_id" value="<?php echo $this->userId;?>"/>    
<div class="basGrid" style="width:500px;">
    <table>
        <thead>
            <th colspan="2">User Information</th>
            
        </thead>
        <tr>
            <td>First name</td>
            <td><?php echo $this->user->first_name?></td>
        </tr>
        <tr>
            <td>Last name</td>
            <td><?php echo $this->user->last_name?></td>
        </tr>
        <tr>
            <td>Email address</td>
            <td><?php echo $this->user->email_address?></td>
        </tr>
        <tr>
            <td>Type</td>
            <td><?php echo $this->user->type?></td>
        </tr>
        <tr>
            <td>Project</td>
            <td>
                <select name="project_id">
                    <?php foreach($this->projectList as $project):?>
                    <option value = "<?php echo $project->id?>"><?php echo $project->name?></option>
                    <?php endforeach; ?>
                </select>
                <input type="submit"  value="Assign"/>
            </td>
        </tr>
    </table>
</div>
</form> 
<div style="width:500px;">
    <div class="title">Assigned project</div>
    <?php 
    echo $this->headScript(); 
    echo $this->grid; 
    ?>
</div>
