<?php
    $config = Zend_Registry::get('config');
    $user = Zend_Auth::getInstance()->getIdentity();
?>
<!DOCTYPE html>
<!-- saved from url=(0054)<?php echo $this->url(); ?> -->
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BUG | Dashboard</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.5 -->
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="/css/ionicons.min.css">
        <!-- jvectormap -->
        <link rel="stylesheet" href="/css/jquery-jvectormap-1.2.2.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="/css/_all-skins.min.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script src="/js/ca-pub-4495360934352473.js"></script>
        <!-- jQuery 2.1.4 -->
        <script src="/js/jQuery-2.1.4.min.js"></script>
        <style type="text/css">
            .jqstooltip { 
                position: absolute;
                left: 0px;top: 0px;
                visibility: hidden;
                background: rgb(0, 0, 0) transparent;
                background-color: rgba(0,0,0,0.6);
                filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
                -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
                color: white;font: 10px arial, san serif;
                text-align: left;
                white-space: nowrap;padding: 5px;border: 1px solid white;
                z-index: 10000;}
            .jqsfield { color: white;font: 10px arial, san serif;text-align: left;}
        </style>
    </head>
<body class="skin-blue sidebar-mini" cz-shortcut-listen="true">
<div class="wrapper">

  <header class="main-header">

    <!-- Logo -->
    <a href="<?php echo $config->baseUrl; ?>/dashboard" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>BUG</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>BUG</b>Sniffer</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="<?php echo $this->url(); ?>#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <a href="<?php echo $this->url(); ?>#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                  <li><!-- start message -->
                    <a href="<?php echo $this->url(); ?>#">
                      <div class="pull-left">
                        <img src="/images/<?php echo $user->logo; ?>" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Under construction
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <p>Stay tuned </p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul><div class="slimScrollBar" style="width: 3px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px; background: rgb(0, 0, 0);"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);"></div></div>
              </li>
              <li class="footer"><a href="<?php echo $this->url(); ?>#">See All Messages</a></li>
            </ul>
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                  <li>
                    <a href="">
                      <i class="fa fa-warning text-yellow"></i> Comment added
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <i class="fa fa-users text-red"></i> Feedback needed
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <i class="fa fa-bug text-green"></i> Mantis added
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <i class="fa fa-user text-red"></i> #12345 has been assigned to you
                    </a>
                  </li>
                </ul><div class="slimScrollBar" style="width: 3px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px; background: rgb(0, 0, 0);"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);"></div></div>
              </li>
              <li class="footer"><a href="">View all</a></li>
            </ul>
          </li>
          <!-- Tasks: style can be found in dropdown.less -->
          <li class="dropdown tasks-menu">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-tasks"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 200px;"><ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
                  <li><!-- Task item -->
                    <a href="">
                      <h3>
                          3 Notice need to fix
                        <small class="pull-right">20%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                    <li><!-- Task item -->
                        <a href="">
                            <h3>
                                4 Warning need to fix
                                <small class="pull-right">80%</small>
                            </h3>
                            <div class="progress xs">
                                <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                    <span class="sr-only">80% Complete</span>
                                </div>
                            </div>
                        </a>
                    </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="">
                      <h3>
                        2 error need to fix
                        <small class="pull-right">60%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">60% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->

                  <li><!-- Task item -->
                    <a href="">
                        <h3>
                            Fixed E: #3 N: #2 W: #4
                            <small class="pull-right">40%</small>
                        </h3>
                        <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                <span class="sr-only">40% Complete</span>
                            </div>
                        </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul><div class="slimScrollBar" style="width: 3px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px; background: rgb(0, 0, 0);"></div><div class="slimScrollRail" style="width: 3px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);"></div></div>
              </li>
              <li class="footer">
                <a href="">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/images/<?php echo $user->logo; ?>" class="user-image" alt="User Image">
              <span class="hidden-xs"><?php echo $user->name; ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/images/<?php echo $user->logo; ?>" class="img-circle" alt="User Image">

                <p>
                    <?php echo $user->name; ?>
                  <small>2016</small>
                </p>
              </li>
              <!-- Menu Body -->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<?php echo $this->url(); ?>#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<?php echo $this->url(); ?>/logout" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="<?php echo $this->url(); ?>#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>

    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar" style="height: auto;">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/images/bas.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>BAS Trucks</p>

        </div>
      </div>
      <!-- search form -->
      <form action="<?php echo $this->url(); ?>#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="<?php echo $this->url(); ?>#">
              <i class="fa fa-laptop"></i><span>BASpubweb</span>
          </a>
          <ul class="treeview-menu">
              <li>
                  <a href="<?php echo $config->baseUrl; ?>?node=baspubweb">
                      <i class="fa fa-circle-o"></i>baspubweb
                  </a>
              </li>
            <li><a href="<?php echo $config->baseUrl; ?>?node=baspubweb1"><i class="fa fa-circle-o"></i>baspubweb1<small class="label pull-right bg-red"><?php echo $this->dashboard['baspubweb1']; ?></small></a></li>
            <li>
                <a href="<?php echo $config->baseUrl; ?>?node=baspubweb2"><i class="fa fa-circle-o"></i>baspubweb2<small class="label pull-right bg-red"><?php echo $this->dashboard['baspubweb2']; ?></small></a>
            </li>
          </ul>
        </li>

      <li class="active treeview">
          <a href="<?php echo $config->baseUrl; ?>?node=basprivweb">
              <i class="fa fa-laptop"></i><span>BASprivweb-ERP</span>
          </a>
          <ul class="treeview-menu">
              <li><a href="<?php echo $config->baseUrl; ?>?node=basprivweb"><i class="fa fa-circle-o"></i>basprivweb</a></li>
              <li><a href="<?php echo $config->baseUrl; ?>?node=basprivweb1"><i class="fa fa-circle-o"></i>basprivweb1<small class="label pull-right bg-red"><?php echo $this->dashboard['basprivweb1']; ?></small></a></li>
              <li>
                  <a href="<?php echo $config->baseUrl; ?>?node=basprivweb2"><i class="fa fa-circle-o"></i>basprivweb2<small class="label pull-right bg-red"><?php echo $this->dashboard['basprivweb2']; ?></small></a>
              </li>
          </ul>
      </li>

      <li class="active treeview">
          <a href="<?php echo $config->baseUrl; ?>?node=basprivwebesb">
              <i class="fa fa-laptop"></i><span>BASprivweb-ESB</span>
          </a>
          <ul class="treeview-menu">
              <li><a href="<?php echo $config->baseUrl; ?>?node=basprivwebesb1"><i class="fa fa-circle-o"></i>basprivweb1<small class="label pull-right bg-red"><?php echo $this->dashboard['basprivwebesb1']; ?></small></a></li>
              <li class="active">
                  <a href="<?php echo $config->baseUrl; ?>?node=basprivwebesb2"><i class="fa fa-circle-o"></i>basprivweb2<small class="label pull-right bg-red"><?php echo $this->dashboard['basprivwebesb2']; ?></small></a>
              </li>
          </ul>
      </li>
      <li>
          <a href="<?php $this->url(); ?>/issue-dashboard">
              <i class="fa fa-th"></i> <span>Issue dashboard</span>
          </a>
      </li>
      <li>
          <a href="<?php $this->url(); ?>/issue-assigned">
              <i class="fa fa-edit"></i> <span>Issue open</span>
              <small class="label pull-right bg-red"></small>
          </a>
      </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="min-height: 921px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
          <?php echo $this->node; ?>
        <small><?php echo date('d-M-Y')?></small>

      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php $this->url(); ?>/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>
    
    <?php echo $this->layout()->content; ?>
    
  </div>
  <!-- /.content-wrapper -->



  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="<?php echo $this->url(); ?>#control-sidebar-theme-demo-options-tab" data-toggle="tab"><i class="fa fa-wrench"></i></a></li><li><a href="<?php echo $this->url(); ?>#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="<?php echo $this->url(); ?>#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job Executed</h4>
                <p>Last execution time : 04-06-2016 12:20 PM</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
        <div id="control-sidebar-theme-demo-options-tab" class="tab-pane active">

        </div>
      <!-- /.tab-pane -->

      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">

      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

</div>

<!-- Bootstrap 3.3.5 -->
<script src="/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/js/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/js/app.min.js"></script>
<!-- Sparkline -->
<script src="/js/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="/js/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/js/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll 1.3.0 -->
<script src="/js/jquery.slimscroll.min.js"></script>
<!-- ChartJS 1.0.1 -->
<script src="/js/Chart.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->

<!-- AdminLTE for demo purposes -->
<script src="/js/demo.js"></script>


<div class="jvectormap-label" style="display: none; left: 400px; top: 665px;">Greenland</div>
</body>
<script src="/js/suggest.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".mantis-btn").click(function() {
            $(this).unbind();
            var trace;
            var id = $(this).attr('id');
            if ($("#stack_trace_"+id).html() != undefined) {
                trace = $("#stack_trace_"+id).html().trim();
            }
            $("#" + id + " i").removeClass('fa-bug');
            $("#" + id + " i").addClass('fa-refresh');
            $("#" + id + " i").addClass('fa-spin');
            addMantis(id, 0, '', 0, '');

        });

        $(".fixed-btn").click(function() {
            var id = $(this).attr('key');
            $(".fixed-btn-" + id).toggle();
            $("#mantis-" + id).hide();
        });

        $(".add-comment").click(function() {
            var id = $(this).attr('key');
            var comment = $("#comment_" + id).val();
            var mantisId = $("#comment_" + id).attr('mantis');
            updateMantis(mantisId, comment, 'Fixed');
        });

    });

    function updateMantis(mantis, comment, status)
    {
        if (comment == '') {
            alert("Please add comment before proceed....");
            return;
        }

        $.ajax({
            method: "POST",
            url: "update-mantis",
            data: {
                mantis_id : mantis,
                comment : comment,
                status : status
            }
        })
        .done(function( msg ) {
            location.reload();
        });
    }

    function addMantis(id, mantis_id, comment, userId, status)
    {
        var trace;
        if ($("#stack_trace_"+id).html() != undefined) {
            trace = $("#stack_trace_"+id).html().trim();
        }

        $.ajax({
            method: "POST",
            url: "add-mantis",
            data: {
                message: $("#message_"+id).html(),
                stack_trace: trace,
                location:$("#location_"+id).html(),
                project : 34,
                error_id : id,
                mantis_id : mantis_id,
                comment : comment,
                userId : userId,
                status : status
            }
        })
        .done(function( msg ) {
            location.reload();
        });
    }

    function assign(that)
    {
        var id = $(that).attr('key');
        var userId = $(that).attr('user');
        addMantis(id, 1, '', userId, 'Open');
    }
    
</script>
</html>