<form method="post" action="<?php echo $this->baseUrl(); ?>/user/auth/forgot-password">
<table style="width:400px;height:200px;margin-top:20px;" cellspacing="0" cellpadding="5">
    <tr style="background-color:#800000;">
        <td nowrap><span style="font-size:30px;color:white;font-weight:bold;">Login</span></td>
        <td></td>
        <td align="right"><img src="<?php echo $this->baseUrl();?>/images/user_login.png" style="width:40px;"></td>
    </tr>
    <tr><td></td></tr>
    <tr>
        <td colspan="2" nowrap>Email address</td>
        <td colspan="2"><input type="textbox" name="email" style="width:300px;font-size:20px;" /></td>
    </tr>
    <tr><td></td></tr>
    <tr style="background-color:#800000;">
        <td colspan="3" style="font-size:30px;color:white;font-weight:bold;"><input type="submit" style="font-size:18px;" value="Submit" /></td>
    </tr>
 </table>
</form>

